<?php
//echo "<pre>";print_r($datos);echo "</pre>";
$borrar_todo = "?controller=Carrito&action=borrarTodo";
?>
<table border='1'>
    <tr>
        <th>ID</th>
        <th>Precio</th>
        <th>Unidades</th>
        <th></th>
        <th></th>
        <?php
        if (isset($_SESSION['carrito'])) {
            echo "<th><a style='' href='$borrar_todo'>Descartar todo</a></th>";
        } ?>
    </tr>
    <?php
    $precio_total = 0;
    $precio_total_producto = 0;
    if (isset($_SESSION['carrito'])) {
        $session = $_SESSION['carrito'];
        require_once "models/utiles/JsonManager.php";
        JsonManager::set_json($session);
        $session = JsonManager::decodificar();
        #verificar si es un solo producto
        if (is_object($session)) {
            $id = $session->id_producto;
            $p = $session->precio;
            $u = $session->unidades;
            $precio_total_producto = $p * $u;
            $precio_total += $precio_total_producto;
            $quitar_producto = "?controller=Carrito&action=quitar&producto=$id";
            $sumar_producto = "?controller=Carrito&action=poner&producto=$id";
            $borrar_producto = "?controller=Carrito&action=borrarUno&producto=$id";
            echo
                "
            <tr>
            <td>$id</td>
            <td>$p</td>
            <td>$u</td>
            <td><a href='$quitar_producto'>-1</a></td>
            <td><a href='$sumar_producto'>+1</a></td>
            <td><a href='$borrar_producto'>Borrar</a></td>
            </tr>
            ";

            echo "<h1>Total de su compra: $precio_total$</h1>";
        } else {
            foreach ($datos as $producto) {
                $id = $producto->id_producto;
                $p = $producto->precio;
                $u = $producto->unidades;
                //Cacular precios
                $precio_total_producto = $p * $u;
                $precio_total += $precio_total_producto;
                //Url para redireccionar
                $quitar_producto = "?controller=Carrito&action=quitar&producto=$id";
                $sumar_producto = "?controller=Carrito&action=poner&producto=$id";
                $borrar_producto = "?controller=Carrito&action=borrarUno&producto=$id";
                echo
                    "
            <tr>
            <td>$id</td>
            <td>$p</td>
            <td>$u</td>
            <td><a href='$quitar_producto'>-1</a></td>
            <td><a href='$sumar_producto'>+1</a></td>
            <td><a href='$borrar_producto'>Borrar</a></td>
            </tr>
            ";


            }
            echo "<h1>Total de su compra: $precio_total$</h1>";
        }

    } else {
        echo "El carrito esta vacio";
    }
    ?>

</table>
<?php echo "<br><a href='index.php?controller=Pedidos&action=hacer'>Hacer pedido</a>" ?>